/**
 * @file CircleAlgorithms.h
 * @brief Declares the Midpoint Circle Algorithm for rasterizing circles.
 *
 * The Midpoint Circle Algorithm (also known as Bresenham's Circle Algorithm)
 * exploits the 8-fold symmetry of a circle to compute one octant of pixels
 * and mirror them into all eight octants simultaneously.
 *
 * This reduces the work to roughly r/√2 iterations (one octant) rather than
 * needing to compute all 2πr pixels independently.
 *
 * Only integer arithmetic is used (no sin/cos), making it very efficient.
 */

#pragma once

#include "PixelBuffer.h"

class CircleAlgorithms {
public:
    /**
     * @brief Draw a circle outline using the Midpoint Circle Algorithm.
     *
     * Starts at (x=0, y=radius) and walks clockwise through the first octant.
     * A decision variable determines whether y should decrease at each step.
     * plotCircleSymmetryPoints() mirrors each computed (x, y) into all 8 octants.
     *
     * @param buffer   Pixel buffer to draw into.
     * @param centerX  Circle centre x (screen coordinates).
     * @param centerY  Circle centre y (screen coordinates).
     * @param radius   Circle radius in pixels.
     * @param color    Colour of the circle outline.
     */
    static void drawCircleMidpoint(
        PixelBuffer& buffer,
        int centerX,
        int centerY,
        int radius,
        Color color
    );

private:
    /**
     * @brief Plot the 8 symmetry points of a circle for a given (x, y) offset.
     *
     * Given one point (centerX+x, centerY+y) on the circle, the other 7
     * symmetry points are generated by reflecting across both axes and swapping
     * x and y:
     *
     *   (+x, +y), (-x, +y), (+x, -y), (-x, -y)   — horizontal axis reflection
     *   (+y, +x), (-y, +x), (+y, -x), (-y, -x)   — diagonal (x↔y) reflection
     *
     * @param buffer   Pixel buffer to draw into.
     * @param centerX  Circle centre x.
     * @param centerY  Circle centre y.
     * @param x        Current octant x offset.
     * @param y        Current octant y offset.
     * @param color    Colour of the plotted pixels.
     */
    static void plotCircleSymmetryPoints(
        PixelBuffer& buffer,
        int centerX,
        int centerY,
        int x,
        int y,
        Color color
    );
};